---
title: "A Variationist Approach to the Expression of Futurity and Epistemicity by Early Spanish-English Bilinguals"
author: "Meritxell Feliu-Ribas"
institute: "Rutgers University"
date: "2024/12/16"
output:
  xaringan::moon_reader:
    css: [default, rutgers, rutgers-fonts]
---

# Futurity and Epistemicity

<div style="font-size: 95%">

* Expression of futurity in Spanish:
    * Complex phenomenon (e.g., Azpiazu, 2024; Escandell-Vidal, 2014, 2019)
    
    * Prime example of diachronic and synchronic variation leading to a language change (Orozco, 2022)
        * Morphological Future (MF): *cantaré*, 'I will sing'
        * Periphrastic Future (PF): *voy a cantar*, 'I am going to sing'
        * Present Indicative (PI): *canto*, 'I sing'
        * Present Progressive (PP): *estoy cantando*, 'I am singing'

* Futurity **&rarr;** Epistemic Modality: <br> *Laura <u>estará</u> en casa*, 'Laura <u>will be</u> at home'; 'Laura <u>must be</u> at home'

* Some definitions:
  * Future: an event or state posterior to the moment of speech (Comrie, 1985; Reichenbach, 1947)
  
  * Epistemicity: speaker's level of certainty toward the utterance (Gennari, 2000; Kearns, 2011)
  
---
<div style="font-size: 95%">

#### <span style="color: #cc0033;">Future-time reference</span>

* Two main trends documented across Spanish varieties in oral speech (for some exceptions, see Díaz-Peralta & Almeida, 2000):

    * PF as the preferred form to express futurity
    
    * MF as gradually decreasing

* Forms constrained by the same linguistic factors cross-dialectally, being temporal distance and plan certainty two of the most relevant (e.g., Aaron, 2014; Orozco, 2015; Claes & Ortiz López, 2011)
    
    * MF: distant or unbounded futures, contexts of uncertainty
    * PF: immediate and near futures, contexts of certainty
    * PI: immediate and near futures (contexts of certainty?)
    * PP: immediate futures, contexts of certainty
    
* Social factors?

#### <span style="color: #cc0033;">Epistemic modality</span>

* Seems to be acquired earlier than prospective MF (Kernan & Bloun, 1966; Trigo Cutiño, 1980)

* MF mainly used as an epistemic marker (Aaron 2007, 2010, 2014)


---
<div style="font-size: 95%">

<div style="margin-top: 25px;"></div>

  <div style="text-align: left; font-weight: bold; color: #cc0033;">
    <span style="font-size: 40px;">&#8595;</span> 
  </div>
    
What about early bilinguals (i.e., *heritage speakers*)?

* Scarce research (only: Durán Urrea & Gradoville, 2006, 2008; Pascual y Cabo & Vela, 2020; Perez-Cortes, 2012; Prada Pérez et al., 2021; Torres, 2024)
    
* Methodological limitations:

    * No circumscription of the envelope of variation
    
    * Tasks measuring acceptability over real language use
    
    * No control of important predictors (e.g., lexical aspect, grammatical person)
    
    * Potential priming of forms
    
    * No inferential stats
    
* Documentation of several trends that warrant further investigation

---
# The Current Project

<div style="font-size: 95%">

Four goals **&rarr;** Three studies:

1. Focus on synchronic variation in language contact situations **&rarr;** early Spanish-English bilinguals in the U.S.

2. Examine the linguistic factors that constrain the uses of the MF, the PF, and the PI with both future and epistemic readings (Study 1)

3. Explore the variable use of the PI and the PP in contexts of futurity (Study 2)

4. Analyze the knowledge of the prospective and epistemic MF to better understand the semantic-pragmatic values that early bilinguals associate with this form (Study 3)

---
# Study 1

<div style="font-size: 95%">

.black[Goal:] To examine the synchronic variation of the canonical forms to express futurity in Spanish by U.S. early Spanish-English bilinguals

### Research Questions

1. What are the rates of use of the MF, the PF, and the PI with future readings among early Spanish-English bilinguals in the U.S.?

2. a) What are the effects of temporal distance, grammatical person, and verb class on the uses of these three forms? <br>
  
  b) Is there an interaction between temporal distance and grammatical person in the use of the MF, the PF, and the PI?
  
3. Are the MF, the PF, and/or the PI used to convey epistemicity among these speakers? 

4. What is the effect of adverb specification, verb class, and type of bilingualism on the epistemic uses of these forms? 

---
<div style="font-size: 95%">

### Methods

* *Corpus del Español en Arizona, CESA* (Carvalho, 2012-) and *Spanish in Texas Corpus, STC* (Bullock & Toribio, 2024)

* Preliminary analysis using 'spaCy' (Honnibal et al., 2020), open-source library for NLP in Python &rarr; 2,491 data points
    * 475 tokens for the MF
    * 2,016 tokens for the PF
    * PI not included &rarr; 'spaCy' not trained to detect pragmatic nuances

* Envelope of variation &rarr; The context in which the forms selected for the analysis are “functionally parallel as well as variable” (Tagliamonte, 2012, p. 10):
    * Futurity
    * Epistemic modality

* Tokens coded for semantic and pragmatic factors (e.g., grammatical person), and social factors (e.g., age)

???
Coding procedure: 
  * Linguistic factors:
      * Reading: prospective, epistemic
      * Form: MF, PF, PI
      * Temporal distance: immediate, close, distant
      * Grammatical person (proxy of certainty)
      * Verb class: dynamic, motion, stative, psychological, perceptual
      * Adverb specification: yes, no
  * Social factors:
      * Participant id
      * Type of bilingualism: sequential, simultaneous
      * Age (continuous measure)

---
<div style="font-size: 95%">

### Statistical Analysis

* Two subsets: future reference uses and epistemic uses 

* Future reference uses:
    * Bayesian multinomial logistic regression model in R (R Core Team, 2022)
    * Form ~ temporal distance + grammatical person + verb class (+ age) + temporal distance:grammatical person

* Epistemic uses:
    * Hard to tell *a priori* 
    * IF a model can be built... <br> Form ~ adverb specification + verb class + type of bilingualism (+ age)
    * IF a model cannot be built... <br> Descriptive stats + cross-tabulation of factors

* Contributions to theories of language variation and grammaticalization

---
# Study 2

<div style="font-size: 95%">

.black[Goal:] To examine the reported preference for the expression of futurity in Spanish by U.S. early Spanish-English bilinguals, with a focus on less studied forms in previous research (i.e., PF, PI, and PP)

### Research Questions

1. To what degree do early Spanish-English bilinguals in the U.S. report preference for the use of the PF, the PI, and the PP to express futurity?

2. What effect do temporal reference and plan certainty have on the reported usage preferences of these forms, and is there a relationship between these factors? 

3. a) How do the results of the bilinguals compare to those of Spanish monolinguals? <br>
  
  b) If there are differences between groups, can they be better explained by contact with English or by an internally motivated change in progress in the Spanish language?

---
<div style="font-size: 95%">

### Participants

* A minimum of 60 early Spanish-English bilinguals

    * Requirements to participate:
        * Be 18 years of age or older
        * Born and/or raised in the U.S.
        * Grew up speaking Spanish or Spanish and English at home
        * Live in the U.S.

* A minumum of 21 Spanish monolinguals

    * Requirements to participate:
        * Be 18 years of age or older
        * Born and/or raised in a Spanish monolingual household
        * Born and/or raised in a Spanish-speaking country
        * Live in a Spanish-speaking country

### Materials

* Bilingual Language Profile (Birdsong et al., 2012)

* Rating Task

---
<div style="font-size: 95%">

#### Rating Task
* Contextualized stories followed by a sentence with the PF, the PI, or the PP

* Participants will be asked to rate how likely it is for them to say that sentence using a 100-point sliding scale

* Items controlled for clause type, person, verb type, and polarity 

* Items manipulated for

    * Verb form: PF, PI, PP
    * Temporal distance: immediate, close, distant
    * Plan certainty: certain, uncertain

* A total of 36 contexts divided into 6 conditions

      1. Immediate and certain event
      2. Close and certain event
      3. Distant and certain event
      4. Immediate and uncertain event
      5. Close and uncertain event
      6. Distant and uncertain event

---
<br>

<table style="border-collapse: separate;border-spacing: 0px 5px; border: 0; background-color: white !important;">
 <thead>
  <tr>
   <th style="font-size:17.75px; text-align:left; height:21pt; background-color: white !important; width:10%;">  </th>
   <th style="font-size:17.75px; text-align:left; background-color: white !important; width:90%;"> [immediate, certain] </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> <b>Context</b> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> Mateo y Laura terminaron los deberes y hablan de sus planes. </td>
  <tr>
   <td style="font-size:17.5px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.5px; text-align:left; background-color: white !important;"> ‘Mateo and Laura finished their homework and talk about their plans.<br><br></td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> Mateo, que ya lo ha decidido, le dice: </td>
   </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> Mateo, who has already decided, says:’ <br><br></td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> <b>Sentence</b> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 1. En 5 minutos voy a jugar al fútbol. </td>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 1. ‘I am going to play soccer in 5 minutes.’ <br><br></td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 2. En 5 minutos juego al fútbol. </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 2. ‘I play soccer in 5 minutes.’ <br><br></td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 3. En 5 minutos estoy jugando al fútbol. </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 3. ‘I am playing soccer in 5 minutes.’ <br><br></td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> <b>Task</b> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> ¿Cómo de probable es que tú digas esta frase? </td>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> ‘How likely are you to say this sentence?’ </td>
  </tr>
</tbody>
</table>

---
<br>

<table style="border-collapse: separate; border-spacing: 0px 5px; border: 0; width: 100%; background-color: white !important;">
 <thead>
  <tr>
   <th style="font-size:17.75px; text-align:left; height:21pt; width:10%; background-color: white !important;"> </th>
   <th style="font-size:17.75px; text-align:left; width:90%; background-color: white !important;"> [distant, uncertain] </th>
  </tr>
 </thead>
 <tbody>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> <b>Context</b> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> El consejero académico le pregunta a Sara qué clases está pensando </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> ‘The academic advisor asks Sara what classes she is planning on <br><br></td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> tomar el próximo año. Ella, aunque no está del todo segura, contesta:</td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> taking next year. Although she is not completely sure, she replies:<br><br></td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> <b>Sentence</b> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 1. El año que viene voy a tomar biología. </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 1. ‘I am going to take biology next year.’ <br><br></td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 2. El año que viene tomo biología. </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 2. ‘I take biology next year.’ <br><br></td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 3. El año que viene estoy tomando biología. </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> 3. ‘I am taking biology next year.’ <br><br></td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> <b>Task</b> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> ¿Cómo de probable es que tú digas esta frase? </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background-color: white !important;"> ‘How likely are you to say this sentence?’ </td>
  </tr>
 </tbody>
</table>

---
<div style="font-size: 95%">

* A total of 218 items:

    * 108 target stimuli
    * 108 distractors
    * 2 traning items
    
* Targets and distractors will be combined and divided into 3 lists

* Each participant will be presented with 74 items:

    * 36 target stimuli
    * 36 distractors
    * 2 traning items

* Feedback from external member (Prof. Naomi Shin)

### Statistical Analysis

* Bayesian linear regression model in R (R Core Team, 2022)

* Rating ~ verb form \* temporal distance \* plan certainty \* group

* Contributions to theories of language variation and grammaticalization

---
# Study 3

<div style="font-size: 95%">

.black[Goal:] To examine the knowledge of the semantic values of the Spanish MF by U.S. early Spanish-English bilinguals

### Research Questions

1. a) Do early Spanish-English bilinguals distinguish between prospective and epistemic uses of the MF when presented with competing interpretations? <br>

  b) Is their interpretation of the MF modulated by Spanish proficiency?

2. How do their interpretations compare with those of monolinguals speakers of Spanish?

---
<div style="font-size: 95%">

### Participants

* A minimum of 60 early Spanish-English bilinguals

    * Requirements to participate:
        * Be 18 years of age or older
        * Born and/or raised in the U.S.
        * Grew up speaking Spanish or Spanish and English at home
        * Live in the U.S.

* A minimum of 20 Spanish monolinguals

    * Requirements to participate:
        * Be 18 years of age or older
        * Born and/or raised in a Spanish monolingual household
        * Born and/or raised in a Spanish-speaking country
        * Live in a Spanish-speaking country

* Participants from Study 2 will be able to participate if they express their willingness

---
<div style="font-size: 95%">

### Materials

* Bilingual Language Profile (Birdsong et al., 2012)

* LexTale-Esp (Izura et al., 2014)

* Forced Choice Interpretation Task

    * Contextualized stories followed by a sentence with the MF and two potential interpretations of the sentence
    
    * Participants will be asked to choose the more accurate interpretation given the context
    
    * Items controlled for clause type, person, verb type, and polarity
    
    * Manipulated for context: prospective, epistemic
    
    * In total, 24 items:
    
        * 10 target stimuli
        * 12 distractors
        * 2 traning items

---
<br>

<table style="border-collapse: separate;border-spacing: 0px 5px; border: 0;background: white !important;">
 <thead>
  <tr>
   <th style="font-size:17.75px; text-align:left; height:21pt; background: white !important; width:10%;">  </th>
   <th style="font-size:17.75px; text-align:left; background: white !important; width:90%;"> [Epistemic reading] </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> <b>Context</b> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> Ricardo nunca falta a clase, pero hoy no ha ido. La profesora </td>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> ‘Ricardo never misses class, but he has not come today. The teacher <br><br> </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> le pregunta a Juan qué le pasa, </td>
   </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> asks Juan if he knows what might be wrong with him, <br><br> </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> pero no lo sabe. Juan le contesta: </td>
   </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> but Juan does not know. He answers:’ <br><br> </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> <b>Sentence</b> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> Estará enfermo. </td>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> ‘He must be sick.’ <br><br> </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> <b>Task</b> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> A. Juan piensa que Ricardo está enfermo. </td>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> A. ‘Juan thinks that Ricardo is sick.’ <br><br> </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> B. Juan piensa que Ricardo va a estar enfermo. </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> B. ‘Juan thinks that Ricardo will be sick.’ </td>
  </tr>
</tbody>
</table>

---
<br>

<table style="border-collapse: separate;border-spacing: 0px 5px; border: 0;background: white !important;">
 <thead>
  <tr>
   <th style="font-size:17.75px; text-align:left; height:21pt; background: white !important; width:10%;">  </th>
   <th style="font-size:17.75px; text-align:left; background: white !important; width:90%;"> [Futurity reading] </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> <b>Context</b> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> El padre de María le pregunta a su mujer qué planes tiene su hija </td>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> ‘María’s father asks her wife what plans their daughter has <br><br> </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> el fin de semana. Como la hija aún no tiene nada planeado, </td>
   </tr>
  <tr>
   <td style="font-size:17.24px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.24px; text-align:left; background: white !important;"> for the weekend. Since the daughter doesn't have anything planned yet, <br><br> </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> la madre le comenta: </td>
   </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> the mother says:’ <br><br> </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> <b>Sentence</b> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> Estará en casa. </td>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> ‘She will be at home.’ <br><br> </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> <b>Task</b> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> A. La madre piensa que su hija está en casa. </td>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> A. ‘The mother thinks that her daughter is at home.’ <br><br> </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> B. La madre piensa que su hija va a estar en casa. </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> </td>
   <td style="font-size:17.75px; text-align:left; background: white !important;"> B. ‘The mother thinks that her daughter will be at home.’ </td>
  </tr>
</tbody>
</table>

    
---
<div style="font-size: 95%">

### Statistical Analysis

* Bayesian binomial regression model in R (R Core Team, 2022)

* Choice ~ condition + Spanish proficiency + group

* Contributions to heritage language acquisition theories

---
# Significance of the Project

<div style="font-size: 95%">

* Hispanic Linguistics **&rarr;** Future-time reference and epistemic modality as two of the most discussed topics in theoretical linguistics

* Variationist Sociolinguistics:
    * Language change and synchronic variation in language contact situations
    * Examination of structured variation within heritage grammars 

* Grammaticalization Theory **&rarr;** Exploration of pathways of change in the expression of futurity

* Heritage Language Acquisition Theories **&rarr;** Interface phenomena

* Methodological Implications:
    * Avoid the priming of certain forms
    * Control for factors that might impact the results
    * Inferential statistics; Bayesian Data Analysis

---
# Proposed Outline

<div style="font-size: 95%">

* .black[Chapter 1:] Introduction to the Phenomena - Problem, rationale, goals, scope
  
* .black[Chapter 2:] Theoretical Frameworks of Grammaticalization and <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Language Variation

* .black[Chapter 3:] Heritage Language Acquisition Theories 

* .black[Chapter 4:] Study 1 - Corpus Study

* .black[Chapter 5:] Study 2 - Rating Task

* .black[Chapter 6:] Study 3 - Semantic Interpretation Task

* .black[Chapter 7:] Conclusions - Theorical implications, limitations, future lines <br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; of research

---
exclude: true

# Estimated Timeline

<table style="border-collapse: separate;border-spacing: 0px 5px; border: 0; margin-top: -20px;">
 <thead>
  <tr>
   <th style="font-size:17.75px; text-align:center; height:21pt;"> Description </th>
   <th style="font-size:17.75px; text-align:center;width:165px;"> Month </th>
   <th style="font-size:17.75px; text-align:center;"> Year </th>
  </tr>
 </thead>
<tbody>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> Dissertation proposal defense </td>
   <td style="font-size:17.75px; text-align:center;"> December </td>
   <td style="font-size:17.75px; text-align:center;"> 2024 </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> Data collection, codification, and preliminary analysis (Study 1) </td>
   <td style="font-size:17.75px; text-align:center;"> December-January </td>
   <td style="font-size:17.75px; text-align:center;"> 2024-2025 </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> IRB Protocol; Data analysis (Study 1) </td>
   <td style="font-size:17.75px; text-align:center;"> January </td>
   <td style="font-size:17.75px; text-align:center;"> 2025 </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> Data analysis; result and discussion sections (Study 1) </td>
   <td style="font-size:17.75px; text-align:center;"> January-March </td>
   <td style="font-size:17.75px; text-align:center;"> 2025 </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> Design and pilot of Studies 2 and 3; <br> Potential changes in the design of the studies
 </td>
   <td style="font-size:17.75px; text-align:center;"> January-February </td>
   <td style="font-size:17.75px; text-align:center;"> 2025 </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> Chapter 2 </td>
   <td style="font-size:17.75px; text-align:center;"> March-May </td>
   <td style="font-size:17.75px; text-align:center;"> 2025 </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> Data collection and preliminary analysis (Studies 2 and 3) 
   </td>
   <td style="font-size:17.75px; text-align:center;"> March-June </td>
   <td style="font-size:17.75px; text-align:center;"> 2025 </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> Data analysis; result and discussion sections (Study 2) </td>
   <td style="font-size:17.75px; text-align:center;"> June-August </td>
   <td style="font-size:17.75px; text-align:center;"> 2025 </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> Data analysis; result and discussion sections (Study 3)
 </td>
   <td style="font-size:17.75px; text-align:center;"> August-October </td>
   <td style="font-size:17.75px; text-align:center;"> 2025 </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> Chapters 1 and 7 </td>
   <td style="font-size:17.75px; text-align:center;"> November-December </td>
   <td style="font-size:17.75px; text-align:center;"> 2025 </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> Send out for revisions </td>
   <td style="font-size:17.75px; text-align:center;"> January </td>
   <td style="font-size:17.75px; text-align:center;"> 2026 </td>
  </tr>
  <tr>
   <td style="font-size:17.75px; text-align:left;"> Defense </td>
   <td style="font-size:17.75px; text-align:center;"> March </td>
   <td style="font-size:17.75px; text-align:center;"> 2026 </td>
  </tr>
</tbody>
</table>

---
# References

<div style="padding-left: 2em; text-indent: -2em;">

<font size="4.90">  

<p>Aaron, J. E. (2007). El futuro epistémico y la variación: Gramaticalización y expresión de la futuridad desde 1600. <i>Moenia, 13</i>, 253–274.</p>

<p>Aaron, J. E. (2010). Pushing the envelope: Looking beyond the variable context. <i>Language Variation and Change, 22</i>(1), 1–36. https://doi.org/10.1017/S0954394509990226</p></p>

<p>Aaron, J. E. (2014). A Certain Future: Epistemicity, Prediction, and Assertion in Iberian Spanish Future Expression. <i>Studies in Hispanic and Lusophone Linguistics, 7</i>(2), 215–240. https://doi.org/10.1515/shll-2014-1166</p></p>

<p>Azpiazu, S. (2024). Evidentiality, epistemic modality and temporality in the Spanish verbal system. In J. Egetenmeyer, S. Dessì Schmid, & M. G. Becker (Eds.), <i>Tense, aspect and discourse structure</i> (pp. 123–150). De Gruyter. https://doi.org/10.1515/9783111453897-005</p>

<p>Birdsong, D., Gertken, L. M., & Amengual, M. (2012). <i>Bilingual Language Profile: An Easy-to-Use Instrument to Assess Bilingualism</i>. COERLL, University of Texas at Austin. https://sites.la.utexas.edu/bilingual/ </p>

<p>Bullock, B. E., & Toribio, A. J. (2024). <i>Spanish in Texas Corpus</i> [Dataset]. Texas Data Repository.</p>

---
<div style="padding-left: 2em; text-indent: -2em;">

<font size="4.90"> 

<p>Carvalho, A. M. (2012). <i>Corpus del Español en el Sur de Arizona (CESA)</i> [Dataset]. University of Arizona.</p>

<p>Claes, J., & Ortiz López, L. A. (2011). Restricciones Pragmáticas y Sociales en la Expresión de Futuridad en el Español de Puerto Rico. <i>Spanish in Context, 8</i>, 50–72.</p>

<p>Comrie, B. (1985). <i>Tense.</i> Cambridge University Press.</p>

<p>Díaz-Peralta, M., & Almeida, M. (2000). Sociolinguistic Factors in Grammatical Change: The Expression of the Future in Canarian Spanish. <i>Studia Neophilologica</i>, 72(2), 217–228. https://doi.org/10.1080/003932700458072 </p>

<p>Durán Urrea, E., & Gradoville, M. (2006). Variation in the Future Tense of New Mexican Spanish. <i>Texas Linguistics Forum, 50 (SALSA XIV Proceedings)</i>.</p>

<p>Durán Urrea, E., & Gradoville, M. (2008). De la futuridad a la epistemicidad: La situación actual del tiempo futuro en el español de Nuevo México. In R. M. Ortiz Ciscomani (Ed.), <i>IX Encuentro Internacional de Lingüística en el Noroeste.</i> (1a ed). Encuentro Internacional de Lingüística en el Noroeste, Hermosillo, Sonora, México. Editorial Unison.</p>

<p>Escandell-Vidal, M. V. (2014). Evidential futures: The case of Spanish. In P. De Brabanter, M. Kissine, & S. Sharifzadeh (Eds.), <i>Future Times, Future Tenses</i> (1st ed., pp. 219–246). Oxford University Press. https://doi.org/10.1093/acprof:oso/9780199679157.003.0010 </p>

<p>Escandell-Vidal, M. V. (2019). Simple Future of Spanish. Natural System Versus Cultivated Uses. <i>Verba Hispanica</i>, 26(1), 15–33. https://doi.org/10.4312/vh.26.1.15-33 </p>

---
<div style="padding-left: 2em; text-indent: -2em;">

<font size="4.90"> 

<p>Gennari, S. (2000). Semantics and Pragmatics of Future Tenses in Spanish. In H. Campos, E. Herburger, A. Morales-Front, & T. J. Walsh (Eds.), <i>Hispanic Linguistics at the turn of the Millennium</i> (pp. 264–281). Cascadilla Press.</p>

<p>Honnibal, M., Montani, I., Van Landeghem, S., & Boyd, A. (2020). <i>spaCy: Industrial-strength Natural Language Processing in Python</i> [Computer software]. https://doi.org/10.5281/zenodo.1212303 </p>

<p>Izura, C., Cuetos, F., & Brysbaert, M. (2014). Lextale-Esp: A test to rapidly and efficiently assess the Spanish vocabulary size. <i>Psicológica, 35</i>, 49–66.</p>

<p>Kearns, K. (2011). <i>Semantics</i> (2nd ed.). Palgrave Macmillan.</p>

<p>Kernan, K. T., & Bloun, B. G. (1966). The Acquisition of Spanish Grammar by Mexican Children. <i>Anthropological Linguistics, 8</i>(9).</p>

<p>Orozco, R. (2022). The expression of futurity in Spanish: An empirical investigation. In M. Díaz-Campos (Ed.), <i>The Routledge Handbook of Variationist Approaches to Spanish</i> (pp. 315–327). Routledge.</p>

<p>Orozco, R. (2015). Castilian in New York City: What can we learn from the future? In S. Sessarego & M. González-Rivera (Eds.), <i>New Perspectives on Hispanic Contact Linguistics in the Americas</i> (pp. 347–372). Iberoamericana Vervuert. https://doi.org/10.31819/9783954878314-017 </p>

<p>Pascual y Cabo, D., & Vela, G. (2020). Futurity and probability in Spanish as a heritage language. In A. Morales-Front, M. J. Ferreira, R. P. Leow, & C. Sanz (Eds.), <i>Issues in Hispanic and Lusophone Linguistics</i> (Vol. 26, pp. 286–302). John Benjamins Publishing Company. https://doi.org/10.1075/ihll.26.14cab </p>

---
<div style="padding-left: 2em; text-indent: -2em;">

<font size="4.90"> 

<p>Perez-Cortes, S. (2012). The interpretation of the present progressive aspectual features by L2 Spanish learners and heritage language speakers. <i>Arizona Working Papers in SLA & Teaching, 19</i>, 36–55.</p>

<p>Prada Pérez, A. D., Gómez Soler, I., & Feroce, N. (2021). Variable Future-Time Expression in Spanish: A Comparison between Heritage and Second Language Learners. <i>Languages, 6</i>(4), 206. https://doi.org/10.3390/languages6040206 </p>

<p>R Core Team. (2022). <i>R: A Language and Environment for Statistical Computing</i>. https://www.R-project.org/ </p>

<p>Reichenbach, H. (1947). <i>Elements of Symbolic Logic</i>. The Macmillan Company.</p>

<p>Tagliamonte, S. A. (2012). <i>Variationist Sociolinguistics: Change, Obervation, Interpretation</i>. Wiley-Blackwell.</p>

<p>Torres, C. (2024). La alternancia en las expresiones del futuro en el español de hablantes de origen hispano en Houston, Texas. <i>Revista de Filología y Lingüística de la Universidad de Costa Rica, 50</i>(1). https://doi.org/10.15517/rfl.v50i1.57568 </p>

<p>Trigo Cutiño, J. M. (1980). Análisis del sistema verbal infantil. <i>Cauce, 3</i>, 107-127.</p>

---
class: center, middle

# <span style="font-size: 80px;"> Thank you!</span>

# <span style="font-size: 80px;"> ¡Gracias!</span>

