# Speaker notes (script)

Good morning, everyone! I will present to you my dissertation proposal, which is a variationist study on the expression of futurity and epistemic modality among early Spanish-English bilinguals.


# Futurity and Epistemicity
The expression of futurity in Spanish is a complex phenomenon that has been intensively studied in both theoretical and applied linguistics, and it is a prime example of diachronic and syncrhonic linguistic variation leading to a language change, as future-time reference can be expressed using a variety of forms such as the MF, the PF, the PI, and the PP, among others.

Closely related to futurity is the epistemic modality, since some theoretical and experimental linguists consider that the MF in particular should no longer be considered a marker of futurity, but, rather, of probability. 

In this presentation, I will interpret ‘future’ as an event or state that is posterior to the moment of speech, and, following Reichenbach's (1947) model, I will assume that the event time and the reference time coincide. So, when using the terms ‘future’ and ‘futurity’, I will refer to the notion of time itself. 

As for the epistemic modality, I will interpret it as the speaker’s level of certainty towards the event, or the probability of the event being true. Importantly, this event coincides with the speech time and, thus, does not receive a futurity reading, but a present one. 


## Future-time reference
As for the expression of futurity, two main trends have been documented across Spanish monolingual communities in oral speech: (1) the PF is generally the preferred form to express future-time reference, and (2) the use of the MF is gradually decreasing, as this form is more frequently used to express probability.

In addition, the studies have identified several key linguistic factors that constrain the uses of the forms to express futurity, being temporal distance and plan certainty two of the most relevant. For example, the MF is generally favored in distant, unbounded, and uncertain plans, whereas the PF, the PI, and the PP are preferred in near futures and contexts of certainty. 

As for the social factors, there have been contradictory results, so it is not well understood, at least, for now, if the expression of futurity is socially constraint. 

## Epistemic modality
In regard to the expression of the epistemic modality, we don't know much. It is known, though, that children acquire the probabilistic MF earlier than the prospective one, and that, among adults, the MF is mainly used to convey probability, despite some exceptions in some specific speech communities. 

## What about early bilinguals
Despite many studies on monolingual speakers, little is known about the expression of futurity and epistemic modality by early Spanish-English bilinguals. In addition, studies that address this issue in bilingual populations are often subject to methodological limitations; for example, they do not consider nor circumscribe the envelope of variation, or they do not control for important factor in the experimental design. 

Despite promising observations in previous literature, such as that the PI and the PP might be undergoing grammaticalization and that language contact situations accelerate internally-motivated changes in the language, research has yet to comprehensively address, using a sound methodology informed by variationist, grammaticalization, and semantic theories, the expression of futurity and epistemic modality in bilingual populations.


# The Current Project
So, with my dissertation, I aim to fill this gap and, specifically:
- focus on synchronic variation in language contact situations, by offering a more comprehensive approach to understanding the acquisition and use of the forms to express futurity and epistemicity in bilingual populations
- examine the linguistic factors that constrain the uses of the MF, the PF, and the PI with future and epistemic readings
- explore the variable use of the PI and the PP in context of futurity in order to shed some light on the potential grammaticalization of these forms, which has been argued to be faster in situations of language contact
- and, lastly, analyze the knowledge of the prospective and epistemic MF to better understand the semantic-pragmatic values that early bilinguals associate with this form


# Study 1
In the first study, I will examine the synchronic variation of the the MF, the PF, and the PI in the Spanish spoken by early Spanish-English bilinguals.

In particular, I address the following RQs...

## Methods
Data will be extracted from the Corpus del Español en Arizona, and the Spanish in Texas Corpus; two sociolinguistic corpora that were created around the same time and that followed similar methodologies. 

In order to confirm the suitability of this method and the availability of the data, I wrote a script on Phython, using spaCy, that counted tokens of the MF and the PF by using the part-of-speech tagging and the morphologizer. The script selected 475 tokens for the MF and 2,016 for the PF, which makes a total of 2,491 data points in both corpora. 

Two linguistics contexts will be considered the envelope of variation, namely futurity and epistemicity. Even though this is not the most common approach in studies on futurity expression, I have decided to consider both envelopes of variation because the inclusion of the epistemic modality might offer insights into the variable expression of futurity in general, and into the synchronic use of the MF in particular. 

All future-time reference and epistemic tokens will be extracted manually, and coded for semantic, pragmatic, and social factors. 

## Statistical Analysis 
The data will be analyzed in two subsets, one for each envelope of variation.

For the future readings, the data will be analyzed using a Bayesian multinomial logistic regression model in R (R Core Team, 2022) that will analyze verb form as a function of temporal distance, grammatical person, and verb class, plus a two-way interaction between temporal distance and grammatical person. 

As for the context of epitemicity, if the verb form has more than one level, I will build a binomial (MF, PF/PI) or multinomial model (MF, PF, PI) that will analyze verb form as a function of adverb specification, verb class, and type of bilingualism (sequential, simultaneous). In case that there is only one form employed with such meaning (e.g., only the MF), I will provide descriptive statistics through cross-tabulation of factors. 

The results from this study will contribute to our knowledge of the synchronic variation in the expression of futurity and epistemic modality among early Spanish-English bilinguals in the U.S., thus informing theories of grammaticalization and language change and variation in bilingual communities.


# Study 2
In the second study, I will examine the reported preference for the expression of futurity in Spanish by early Spanish-English bilinguals, with a focus on less studied forms that might be undergoing grammaticalization. 

Specifically, I address these RQs...

## Participants
A minimum of 60 early Spanish-English bilinguals from the U.S. will be recruited for this study. 

In order to explore if there are innovative uses among the bilinguals and the nature of such uses, there will be a control group comprised by Spanish speakers. 

Importantly, I will try to match the monolingual group with the bilingual group especially in terms of age and Spanish varieties. 

## Materials
Drawing from similar methodologies used in previous studies that focused on the use of variable structures in Spanish, participants will complete the Bilingual Language Profile, and the experimental task using Quatrics. 

In the experimental task, participants will read a context followed by a sentence with either the PF, the PI, or the PP, and will be asked to rate, using a 100-point sliding scale, how likely it is for them to say that sentence. 

The items will be controlled for clause type, person, verb type, and polarity, and will be manipulated for verb form, temporal distance, and plan certainty.

I will create a total of 36 contexts, that will be divided into six conditions, being each condition a unique combination of temporal reference and plan certainty.

There will be a total of 108 target stimuli, a proportional number of distractors, and two training items. The targets and the distractions will be combined and divided into three lists, and participants will be presented with one of the lists, that is, 74 items.

Before moving to the statistical analysis, I actually have a comment that I would like to address to my committee. Recent, outside feedback suggested adding a version of the task in English and having bilinguals complete both. Even though this suggestion make sense based on the goals of the dissertation, I haven't had enough time to fully implement it, but I intend to do so in the future; so maybe it is something that we could talk about during the questions session. 


## Statistical Analysis
**The data will be analyzed using a Bayesian linear regression model in R that will analyze rating as a function of verb form, temporal distance, plan certainty, and group, plus a two-way interaction between temporal distance and plan certainty. **

The results from this study will provide detail about less commonly studied forms to express futurity, will contribute to grammaticalization theory by examining the pathways of these alternative forms, and will inform theories of language change and variation in bilingual settings.


# Study 3
In the last study, I will examine the acquisition of the epistemic and prospective MF by early Spanish-English bilinguals. 

In particular, I address the following RQs...

## Participants
As in the previous study, I intend to recruit a minimum of 60 early Spanish-English  bilinguals from the U.S., and a control group of Spanish monolinguals.

Those participants from Study 2 that would like to participate in Study 3 will be able to do so.

## Materials
Participants will complete the Bilingual Language Profile, the experimental task, and the LexTale-Esp using Quatrics.

In the Forced Choice Interpretation Task, participants will read a context followed by a sentence with the MF and two potential interpretations of the sentence, and will be asked to choose the more accurate interpretation given the context. 

The items will be controlled for clause type, person, verb type, and polarity, and will be manipulated for context.

There will be a total of 24 items, 10 of which will be the target stimuli.

## Statistical Analysis
The data will be analyzed using a Bayesian binomial logistic regression model in R (R Core Team, 2022), that will analyze choice as a function of condition, Spanish proficiency, and group.


The results from this study will contribute to heritage language acquisition theories by exploring a complex phenomenon that lies in the interface between morphosyntax and pragmatics.


# Significance of the Project
All right, so let's talk about the significance of my project!

My dissertation aims to contribute to the fields of Hispanic linguistics and heritage language acquisition by addressing two of the most discussed topics in theoretical linguistics: future-time reference, and epistemic modality. 

By taking a variationist approach in the first two studies, I intend to contribute to theories of language change and synchronic variation in language contact situations. In addition, by examining structured variation within heritage grammars, I aim to contribute to the limited body of literature that employs this approach to study the acquisition of heritage languages.

Moreover, this dissertation will make contributions to grammaticalization theory by exploring the pathways of change for less commonly studied paradigms in the expression of futurity, using empirical data from a larger pool of participants. 

Another key contribution of this work, especially Study 3, will lie in the field of heritage language acquisition. Theories of heritage language acquisition suggest that interface phenomena are problematic and vulnerable, especially for bilinguals and adult L2 learners, and are, therefore, prone to incomplete acquisition and attrition.

Lastly, my dissertation will also have methodologically implications. Most of the  studies with early Spanish-English bilinguals have limitations in their methods and, thus, their findings should be interpreted with caution. For example, some of them might have primed the use of certain forms or interpretations; did not control for factors that might had an impact on the results; and/or did not perform inferential statistics and, thus, the effect of the predictors is unknown. My studies will be informed by descriptions from theoretical linguistics and variationist sociolinguistics and will attempt to overcome these methodological limitations. 


# Proposed Outline
Here is the proposed outline


# References
and the references


# Thank you
Thank you! ¡Gracias! 



